services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: qdrant
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ${BASE_PATH}/${APP_PATH}:/qdrant/storage
    networks:
      - qdrant-net
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.rule=Host(`${HOST}.${DOMAIN}`)"
      - "traefik.http.routers.qdrant.entrypoints=websecure"
      - "traefik.http.routers.qdrant.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
      - "traefik.docker.network=traefik-net"

configs:
  qdrant_config:
    content: |
      log_level: INFO

networks:
  qdrant-net:
    external: false
    attachable: true
    name: qdrant-net
  traefik-net:
    external: true
    name: traefik-net